// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID              uuid.UUID `json:"id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	Email           string    `json:"email"`
	HashedPassword  string    `json:"hashed_password"`
	LineID          string    `json:"line_id"`
	Nickname        string    `json:"nickname"`
	IsEmailVerified bool      `json:"is_email_verified"`
	Role            string    `json:"role"`
}
